const table =5
console.log (table*1)
console.log (table*2)
console.log (table*3)
console.log (table*4)
console.log (table*5)
console.log (table*6)
console.log (table*7)
console.log (table*8)
console.log (table*9)
console.log (table*10)